<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="112354" started-at="2020-04-06T11:26:04Z" finished-at="2020-04-06T11:27:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="112354" started-at="2020-04-06T11:26:04Z" finished-at="2020-04-06T11:27:57Z">
      <class name="example.NewTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:example.NewTest@402a079c]" name="beforeTest" is-config="true" duration-ms="23400" started-at="2020-04-06T16:56:04Z" finished-at="2020-04-06T16:56:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="testEasy()[pri:0, instance:example.NewTest@402a079c]" name="testEasy" duration-ms="82839" started-at="2020-04-06T16:56:28Z" finished-at="2020-04-06T16:57:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEasy -->
        <test-method status="FAIL" signature="afterTest()[pri:0, instance:example.NewTest@402a079c]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-04-06T16:57:51Z" finished-at="2020-04-06T16:57:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Jobs - Recruitment - Job Search - Employment - Job Vacancies - Naukri.com] but found [Jobs - Recruitment - Job Search - Employment -Job Vacancies - Naukri.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Jobs - Recruitment - Job Search - Employment - Job Vacancies - Naukri.com] but found [Jobs - Recruitment - Job Search - Employment -Job Vacancies - Naukri.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at example.NewTest.afterTest(NewTest.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.afterRun(TestRunner.java:983)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- example.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
